server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope:
              - internal
            clientId:
            clientSecret:
        provider:
          okta:
            issuerUri:

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelRetryService:
        waitDuration: 2s
        maxAttempts: 3

  ratelimiter:
    instances:
      ratingHotelLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 4
        timeoutDuration: 0s

okta:
  oauth2:
    issuer:
    audience:
    client-id:
    client-secret:
